// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRWeQBbPMXPBSuhJSra-qndEy-cYiHZts',
    appId: '1:828802900311:web:2b7ca77e72790b2a381e12',
    messagingSenderId: '828802900311',
    projectId: 'dreamtoimage-fa6f1',
    authDomain: 'dreamtoimage-fa6f1.firebaseapp.com',
    storageBucket: 'dreamtoimage-fa6f1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChvQdD_v-GxIQ-MzjSl_uuopDVRBeJQSk',
    appId: '1:828802900311:android:313ebc1f45970518381e12',
    messagingSenderId: '828802900311',
    projectId: 'dreamtoimage-fa6f1',
    storageBucket: 'dreamtoimage-fa6f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRAITyxYAO1Il5qvU_7PQy_VA7xvtKgOM',
    appId: '1:828802900311:ios:4de89f63a8dfba43381e12',
    messagingSenderId: '828802900311',
    projectId: 'dreamtoimage-fa6f1',
    storageBucket: 'dreamtoimage-fa6f1.appspot.com',
    iosBundleId: 'com.example.womboApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRAITyxYAO1Il5qvU_7PQy_VA7xvtKgOM',
    appId: '1:828802900311:ios:346dd224aeb50964381e12',
    messagingSenderId: '828802900311',
    projectId: 'dreamtoimage-fa6f1',
    storageBucket: 'dreamtoimage-fa6f1.appspot.com',
    iosBundleId: 'com.example.womboApp.RunnerTests',
  );
}
