import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

class ImageCountPage extends StatelessWidget {
  final int imageCount; // Number of images generated by the user

  ImageCountPage({required this.imageCount});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Color(0xFF6A0DAD),
        foregroundColor: Colors.white,
        title: Text('Image Count'),
      ),
      body: Stack(
        children:[Padding(
          padding: const EdgeInsets.all(16.0),
          child: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              crossAxisAlignment: CrossAxisAlignment.center,
              children: [
               imageCount>0? Image.asset(
                  'assets/images/img2.png', // Replace with your celebration image
                  height: 400,
                ):Image.asset(
                  'assets/images/img1.png', // Replace with your celebration image
                  height: 200,
                ),
                SizedBox(height: 24),
                Text(
                imageCount>0?  'Congratulations!':'oh no!',
                  style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
                ),
               imageCount>0? SizedBox(height: 8):SizedBox(height: 0,),
                Text(
                 imageCount>0? 'You have generated .':"",
                  style: TextStyle(fontSize: 18),
                  textAlign: TextAlign.center,
                ),
                imageCount>0? SizedBox(height: 8):SizedBox(height: 0,),
                Text(
                  ' $imageCount',
                  style: TextStyle(fontSize: 45,
                  color: imageCount>0?Colors.green:Colors.red),
                  
                  textAlign: TextAlign.center,
                ),
                SizedBox(height: 8),
                Text(
                 imageCount>0? 'Image Yet!\nThanks for using me':"You haven't generated any images yet.",
                  style: TextStyle(fontSize: 18),
                  textAlign: TextAlign.center,
                ),
              ],
            ),
          ),
        ),
        ],
      ),
    );
  }
}
